version: '3.7'

services:
  app:
    build:
      context: .
    #ports:
    #  - 8000:8000
    # command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  vols